[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "footy"
version = "0.1.0"
description = "Footy Simulation Engine & FastAPI Backend"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi",
    "uvicorn",
    "watchfiles",
    "sqlalchemy",
    "pydantic",
    "torch",
    "pytest",
    "python-dotenv"
]

[tool.setuptools.packages.find]
where = ["backend/src"]

[tool.pytest.ini_options]
pythonpath = ["backend/src"]
testpaths = ["backend/tests"]
