"""add_performance_indexes_and_foreign_keys

Revision ID: 879f4c01467a
Revises: e3a1b7c92d10
Create Date: 2026-09-06 13:01:24.672694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '879f4c01467a'
down_revision: Union[str, Sequence[str], None] = 'e3a1b7c92d10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Match', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Match_simulation_run_id'), ['simulation_run_id'], unique=False)
        batch_op.create_foreign_key('fk_match_simulation_run_id', 'SimulationRun', ['simulation_run_id'], ['run_id'])

    with op.batch_alter_table('MatchEvent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_MatchEvent_match_id'), ['match_id'], unique=False)

    with op.batch_alter_table('TransferHistory', schema=None) as batch_op:
        batch_op.create_index('ix_transfer_season_year', ['season_year'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TransferHistory', schema=None) as batch_op:
        batch_op.drop_index('ix_transfer_season_year')

    with op.batch_alter_table('MatchEvent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_MatchEvent_match_id'))

    with op.batch_alter_table('Match', schema=None) as batch_op:
        batch_op.drop_constraint('fk_match_simulation_run_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_Match_simulation_run_id'))

    # ### end Alembic commands ###
