"""add_match_season_index_and_report_constraints

Revision ID: dc914aadd948
Revises: c7c6ac0ab9c1
Create Date: 2026-09-03 04:46:37.441742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc914aadd948'
down_revision: Union[str, Sequence[str], None] = 'c7c6ac0ab9c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.batch_alter_table('Match', schema=None) as batch_op:
        batch_op.create_index('ix_match_season_year', ['season_year'], unique=False)

    # Deduplicate existing SeasonReport entries, keeping highest report_id per season_year
    op.execute(
        "DELETE FROM SeasonReport WHERE report_id NOT IN ("
        "  SELECT MAX(report_id) FROM SeasonReport GROUP BY season_year"
        ")"
    )
    with op.batch_alter_table('SeasonReport', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_season_report_season_year', ['season_year'])

    # Deduplicate existing TransferReport entries, keeping highest report_id per season_year
    op.execute(
        "DELETE FROM TransferReport WHERE report_id NOT IN ("
        "  SELECT MAX(report_id) FROM TransferReport GROUP BY season_year"
        ")"
    )
    with op.batch_alter_table('TransferReport', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_transfer_report_season_year', ['season_year'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TransferReport', schema=None) as batch_op:
        batch_op.drop_constraint('uq_transfer_report_season_year', type_='unique')

    with op.batch_alter_table('SeasonReport', schema=None) as batch_op:
        batch_op.drop_constraint('uq_season_report_season_year', type_='unique')

    with op.batch_alter_table('Match', schema=None) as batch_op:
        batch_op.drop_index('ix_match_season_year')

    # ### end Alembic commands ###
