"""Add Season and Transfer reports

Revision ID: f1279028ebae
Revises: 
Create Date: 2026-04-13 01:49:24.892486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1279028ebae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SeasonReport',
    sa.Column('report_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('champion_team', sa.String(), nullable=False),
    sa.Column('report_data', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('TransferReport',
    sa.Column('report_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('season_year', sa.Integer(), nullable=False),
    sa.Column('report_data', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.drop_table('ManagerLineupPlayers')
    op.drop_table('ManagerMarketMemorySuccessPatterns')
    op.drop_table('ManagerEpisodeRewards')
    op.drop_table('ManagerMatchRewards')
    op.drop_table('ManagerMarketStateHistory')
    op.drop_table('ManagerMatchHistory')
    op.drop_table('ManagerLineupHistory')
    op.drop_table('CoachPlayerProgress')
    op.drop_table('ManagerPerformanceHistory')
    op.drop_table('TransferListing')
    op.drop_table('LeagueHistoricalStandings')
    op.drop_table('ManagerFormationPreferences')
    op.drop_table('ManagerQTable')
    op.drop_table('ManagerMemoryUsage')
    op.drop_table('ManagerTransferValueEstimates')
    op.drop_table('MatchShots')
    op.drop_table('TransferHistory')
    op.drop_table('ManagerTransferAttempts')
    op.drop_table('CoachSessionResults')
    op.drop_table('PlayerForm')
    op.drop_table('PlayerInjuryHistory')
    op.drop_table('ManagerMarketMemoryPriceHistory')
    op.drop_table('ManagerMarketMemoryPositionDemand')
    op.drop_table('ManagerMarketLearning')
    op.drop_table('CoachTrainingEffectiveness')
    op.drop_table('ManagerTransferHistory')
    op.drop_table('MatchEvent')
    op.drop_table('ManagerMarketMemorySeasonalFactors')
    op.alter_column('Coach', 'coach_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('Coach', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Coach', 'specialty',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Coach', 'learning_rate',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('Coach', 'exploration_rate',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('League', 'league_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('League', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Manager', 'manager_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('Manager', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Manager', 'formation',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Manager', 'total_rewards',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('ManagerProfile', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('ManagerProfile', 'risk_aversion',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('ManagerProfile', 'financial_preference',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('ManagerProfile', 'youth_preference',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('ManagerProfile', 'aggression',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('ManagerProfile', 'patience',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('ManagerTactics', 'manager_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('Match', sa.Column('home_yellow_cards', sa.Integer(), nullable=False))
    op.add_column('Match', sa.Column('away_yellow_cards', sa.Integer(), nullable=False))
    op.add_column('Match', sa.Column('home_red_cards', sa.Integer(), nullable=False))
    op.add_column('Match', sa.Column('away_red_cards', sa.Integer(), nullable=False))
    op.add_column('Match', sa.Column('home_injuries', sa.Integer(), nullable=False))
    op.add_column('Match', sa.Column('away_injuries', sa.Integer(), nullable=False))
    op.alter_column('Match', 'match_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('Match', 'date',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Match', 'home_possession',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('Match', 'away_possession',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('Match', 'weather',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Match', 'intensity',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.drop_constraint(None, 'Match', type_='foreignkey')
    op.drop_constraint(None, 'Match', type_='foreignkey')
    op.alter_column('Player', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('Player', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Player', 'position',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Player', 'wage',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('Player', 'squad_role',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('PlayerAttributes', 'attribute_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('PlayerAttributes', 'sub_attribute',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('PlayerAttributes', 'value',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('PlayerStats', 'fitness',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('Team', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('Team', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('Team', 'budget',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('Team', 'weekly_budget',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('Team', 'transfer_budget',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('Team', 'wage_budget',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('TeamStatistics', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('TeamStatistics', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Team', 'wage_budget',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('Team', 'transfer_budget',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('Team', 'weekly_budget',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('Team', 'budget',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('Team', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Team', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('PlayerStats', 'fitness',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('PlayerAttributes', 'value',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('PlayerAttributes', 'sub_attribute',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('PlayerAttributes', 'attribute_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Player', 'squad_role',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Player', 'wage',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('Player', 'position',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Player', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Player', 'player_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_foreign_key(None, 'Match', 'Team', ['away_team_id'], ['team_id'])
    op.create_foreign_key(None, 'Match', 'Team', ['home_team_id'], ['team_id'])
    op.alter_column('Match', 'intensity',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Match', 'weather',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Match', 'away_possession',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('Match', 'home_possession',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('Match', 'date',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Match', 'match_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('Match', 'away_injuries')
    op.drop_column('Match', 'home_injuries')
    op.drop_column('Match', 'away_red_cards')
    op.drop_column('Match', 'home_red_cards')
    op.drop_column('Match', 'away_yellow_cards')
    op.drop_column('Match', 'home_yellow_cards')
    op.alter_column('ManagerTactics', 'manager_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('ManagerProfile', 'patience',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('ManagerProfile', 'aggression',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('ManagerProfile', 'youth_preference',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('ManagerProfile', 'financial_preference',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('ManagerProfile', 'risk_aversion',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('ManagerProfile', 'profile_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('Manager', 'total_rewards',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('Manager', 'formation',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Manager', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Manager', 'manager_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('League', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('League', 'league_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('Coach', 'exploration_rate',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('Coach', 'learning_rate',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False)
    op.alter_column('Coach', 'specialty',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Coach', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('Coach', 'coach_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.create_table('ManagerMarketMemorySeasonalFactors',
    sa.Column('manager_id', sa.INTEGER(), nullable=False),
    sa.Column('month', sa.INTEGER(), nullable=False),
    sa.Column('factor', sa.REAL(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['Manager.manager_id'], )
    )
    op.create_table('MatchEvent',
    sa.Column('event_id', sa.INTEGER(), nullable=True),
    sa.Column('match_id', sa.INTEGER(), nullable=False),
    sa.Column('minute', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.TEXT(), nullable=False),
    sa.Column('player', sa.TEXT(), nullable=True),
    sa.Column('team', sa.TEXT(), nullable=True),
    sa.Column('details', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['Match.match_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('ManagerTransferHistory',
    sa.Column('transfer_id', sa.INTEGER(), nullable=True),
    sa.Column('player_id', sa.INTEGER(), nullable=False),
    sa.Column('from_team_id', sa.INTEGER(), nullable=False),
    sa.Column('to_team_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.REAL(), nullable=False),
    sa.Column('day', sa.INTEGER(), nullable=False),
    sa.Column('season_year', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['from_team_id'], ['Team.team_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['Player.player_id'], ),
    sa.ForeignKeyConstraint(['to_team_id'], ['Team.team_id'], ),
    sa.PrimaryKeyConstraint('transfer_id')
    )
    op.create_table('CoachTrainingEffectiveness',
    sa.Column('coach_id', sa.INTEGER(), nullable=False),
    sa.Column('method', sa.TEXT(), nullable=False),
    sa.Column('effectiveness', sa.REAL(), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['Coach.coach_id'], ),
    sa.PrimaryKeyConstraint('coach_id', 'method')
    )
    op.create_table('ManagerMarketLearning',
    sa.Column('market_learning_id', sa.INTEGER(), nullable=True),
    sa.Column('manager_id', sa.INTEGER(), nullable=False),
    sa.Column('price_trends', sa.TEXT(), nullable=False),
    sa.Column('position_demand', sa.TEXT(), nullable=False),
    sa.Column('seasonal_patterns', sa.TEXT(), nullable=False),
    sa.Column('date', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['Manager.manager_id'], ),
    sa.PrimaryKeyConstraint('market_learning_id')
    )
    op.create_table('ManagerMarketMemoryPositionDemand',
    sa.Column('manager_id', sa.INTEGER(), nullable=False),
    sa.Column('position', sa.TEXT(), nullable=False),
    sa.Column('demand_value', sa.REAL(), nullable=False),
    sa.Column('timestamp', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['Manager.manager_id'], )
    )
    op.create_table('ManagerMarketMemoryPriceHistory',
    sa.Column('manager_id', sa.INTEGER(), nullable=False),
    sa.Column('position', sa.TEXT(), nullable=False),
    sa.Column('price', sa.REAL(), nullable=False),
    sa.Column('timestamp', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['Manager.manager_id'], )
    )
    op.create_table('PlayerInjuryHistory',
    sa.Column('injury_id', sa.INTEGER(), nullable=True),
    sa.Column('player_id', sa.INTEGER(), nullable=False),
    sa.Column('injury_type', sa.TEXT(), nullable=False),
    sa.Column('duration', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['Player.player_id'], ),
    sa.PrimaryKeyConstraint('injury_id')
    )
    op.create_table('PlayerForm',
    sa.Column('player_id', sa.INTEGER(), nullable=False),
    sa.Column('form', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['Player.player_id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('CoachSessionResults',
    sa.Column('coach_id', sa.INTEGER(), nullable=False),
    sa.Column('method', sa.TEXT(), nullable=False),
    sa.Column('average_improvement', sa.REAL(), nullable=False),
    sa.Column('players_improved', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['Coach.coach_id'], )
    )
    op.create_table('ManagerTransferAttempts',
    sa.Column('manager_id', sa.INTEGER(), nullable=False),
    sa.Column('attempt_successful', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['Manager.manager_id'], )
    )
    op.create_table('TransferHistory',
    sa.Column('transfer_id', sa.INTEGER(), nullable=True),
    sa.Column('player_id', sa.INTEGER(), nullable=False),
    sa.Column('from_team_id', sa.INTEGER(), nullable=False),
    sa.Column('to_team_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.REAL(), nullable=False),
    sa.Column('day', sa.INTEGER(), nullable=False),
    sa.Column('season_year', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['from_team_id'], ['Team.team_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['Player.player_id'], ),
    sa.ForeignKeyConstraint(['to_team_id'], ['Team.team_id'], ),
    sa.PrimaryKeyConstraint('transfer_id')
    )
    op.create_table('MatchShots',
    sa.Column('match_id', sa.INTEGER(), nullable=False),
    sa.Column('team', sa.TEXT(), nullable=False),
    sa.Column('total', sa.INTEGER(), nullable=False),
    sa.Column('on_target', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['Match.match_id'], ),
    sa.PrimaryKeyConstraint('match_id', 'team')
    )
    op.create_table('ManagerTransferValueEstimates',
    sa.Column('manager_id', sa.INTEGER(), nullable=False),
    sa.Column('player_name', sa.TEXT(), nullable=False),
    sa.Column('estimated_value', sa.REAL(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['Manager.manager_id'], )
    )
    op.create_table('ManagerMemoryUsage',
    sa.Column('memory_usage_id', sa.INTEGER(), nullable=True),
    sa.Column('manager_id', sa.INTEGER(), nullable=False),
    sa.Column('transfer_history_size', sa.INTEGER(), nullable=False),
    sa.Column('market_memory_size', sa.TEXT(), nullable=False),
    sa.Column('value_estimates_size', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['Manager.manager_id'], ),
    sa.PrimaryKeyConstraint('memory_usage_id')
    )
    op.create_table('ManagerQTable',
    sa.Column('manager_id', sa.INTEGER(), nullable=False),
    sa.Column('qtable_type', sa.TEXT(), nullable=False),
    sa.Column('qtable_data', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['Manager.manager_id'], )
    )
    op.create_table('ManagerFormationPreferences',
    sa.Column('formation_preference_id', sa.INTEGER(), nullable=True),
    sa.Column('manager_id', sa.INTEGER(), nullable=False),
    sa.Column('formation', sa.TEXT(), nullable=False),
    sa.Column('preference_weight', sa.REAL(), nullable=False),
    sa.Column('date', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['Manager.manager_id'], ),
    sa.PrimaryKeyConstraint('formation_preference_id')
    )
    op.create_table('LeagueHistoricalStandings',
    sa.Column('historical_standing_id', sa.INTEGER(), nullable=True),
    sa.Column('league_id', sa.INTEGER(), nullable=False),
    sa.Column('season_year', sa.INTEGER(), nullable=False),
    sa.Column('standings', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['League.league_id'], ),
    sa.PrimaryKeyConstraint('historical_standing_id')
    )
    op.create_table('TransferListing',
    sa.Column('listing_id', sa.INTEGER(), nullable=True),
    sa.Column('player_id', sa.INTEGER(), nullable=False),
    sa.Column('asking_price', sa.REAL(), nullable=False),
    sa.Column('selling_team_id', sa.INTEGER(), nullable=False),
    sa.Column('listed_date', sa.INTEGER(), nullable=False),
    sa.Column('expires_in', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['Player.player_id'], ),
    sa.ForeignKeyConstraint(['selling_team_id'], ['Team.team_id'], ),
    sa.PrimaryKeyConstraint('listing_id')
    )
    op.create_table('ManagerPerformanceHistory',
    sa.Column('performance_id', sa.INTEGER(), nullable=True),
    sa.Column('manager_id', sa.INTEGER(), nullable=False),
    sa.Column('total_rewards', sa.REAL(), nullable=False),
    sa.Column('win_rate', sa.REAL(), nullable=False),
    sa.Column('draw_rate', sa.REAL(), nullable=False),
    sa.Column('exploration_rate', sa.REAL(), nullable=False),
    sa.Column('learning_rate', sa.REAL(), nullable=False),
    sa.Column('matches_played', sa.INTEGER(), nullable=False),
    sa.Column('wins', sa.INTEGER(), nullable=False),
    sa.Column('draws', sa.INTEGER(), nullable=False),
    sa.Column('losses', sa.INTEGER(), nullable=False),
    sa.Column('average_reward', sa.REAL(), nullable=False),
    sa.Column('transfer_success_rate', sa.REAL(), nullable=False),
    sa.Column('current_exploration_rate', sa.REAL(), nullable=False),
    sa.Column('date', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['Manager.manager_id'], ),
    sa.PrimaryKeyConstraint('performance_id')
    )
    op.create_table('CoachPlayerProgress',
    sa.Column('coach_id', sa.INTEGER(), nullable=False),
    sa.Column('player_name', sa.TEXT(), nullable=False),
    sa.Column('focus_attribute', sa.TEXT(), nullable=False),
    sa.Column('improvement', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['Coach.coach_id'], )
    )
    op.create_table('ManagerLineupHistory',
    sa.Column('lineup_id', sa.INTEGER(), nullable=True),
    sa.Column('manager_id', sa.INTEGER(), nullable=False),
    sa.Column('match_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['Manager.manager_id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['Match.match_id'], ),
    sa.PrimaryKeyConstraint('lineup_id')
    )
    op.create_table('ManagerMatchHistory',
    sa.Column('manager_id', sa.INTEGER(), nullable=False),
    sa.Column('match_data', sa.TEXT(), nullable=False),
    sa.Column('date', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['Manager.manager_id'], )
    )
    op.create_table('ManagerMarketStateHistory',
    sa.Column('market_state_id', sa.INTEGER(), nullable=True),
    sa.Column('manager_id', sa.INTEGER(), nullable=False),
    sa.Column('market_trend', sa.TEXT(), nullable=False),
    sa.Column('position_demand', sa.TEXT(), nullable=False),
    sa.Column('seasonal_factor', sa.TEXT(), nullable=False),
    sa.Column('date', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['Manager.manager_id'], ),
    sa.PrimaryKeyConstraint('market_state_id')
    )
    op.create_table('ManagerMatchRewards',
    sa.Column('manager_id', sa.INTEGER(), nullable=False),
    sa.Column('reward', sa.REAL(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['Manager.manager_id'], )
    )
    op.create_table('ManagerEpisodeRewards',
    sa.Column('manager_id', sa.INTEGER(), nullable=False),
    sa.Column('reward', sa.REAL(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['Manager.manager_id'], )
    )
    op.create_table('ManagerMarketMemorySuccessPatterns',
    sa.Column('manager_id', sa.INTEGER(), nullable=False),
    sa.Column('pattern_data', sa.TEXT(), nullable=False),
    sa.Column('date', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['Manager.manager_id'], )
    )
    op.create_table('ManagerLineupPlayers',
    sa.Column('lineup_id', sa.INTEGER(), nullable=False),
    sa.Column('player_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['lineup_id'], ['ManagerLineupHistory.lineup_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['Player.player_id'], ),
    sa.PrimaryKeyConstraint('lineup_id', 'player_id')
    )
    op.drop_table('TransferReport')
    op.drop_table('SeasonReport')
    # ### end Alembic commands ###
